### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by dirkmb** [SamuelSorge/RESAUebung2#1]
kann das wieder jemand mit eclipse das schön machen?

**Comment by waljaa** [comment]
Kann ich am Ende wieder machen, muss jetzt aber erst mal noch SystemA zum Laufen bekommen

**Comment by ghost** [comment]
Wann arbeitest du morgen daran? Weil würde es mir auch noch anschauen
Am 17.01.2015 23:48 schrieb "Jaasiel" notifications@github.com:
