### ISSUE TITLE
SystemA: files not added to git

### ISSUE THREAD

**Issue by dirkmb** [SamuelSorge/RESAUebung2#6]
z.b. SecurityConsole fehlt, könnt nochmal gucken was bei euch im Ordner ist aber nicht im git.

**Comment by ghost** [comment]
Hey Dirk,

Habe dir im hip Chat geschrieben.
Da ist etwas beim letzten commit von mir in die Hose gegangen.
Kannst du den rückgängig machen?

Gruß
Am 20.01.2015 19:57 schrieb "Dirk Braunschweiger" <notifications@github.com

**Comment by waljaa** [comment]
Hab schon die fehlenden dateien eingespielt, aber die vorhandenen nicht überschrieben, da die gematched haben (zumindest securitycontroller securtiyconsole und securitymonitor). Hoffe die restlichen dateien sind die richtigen
